 language: java
sudo: false
dist: trusty
jdk: openjdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

